language: python
python:
    - "2.7"
    - "3.5"
script: python -m unittest discover
addons:
    apt:
        packages:
            - ping

branches:
    only: 
        - master

cache: false

notifications:
    email: false
